[PHP]
memory_limit = 256M
upload_max_filesize = 20M
post_max_size = 20M
max_execution_time = 60

[Date]
date.timezone = Europe/Istanbul

[opcache]
opcache.enable = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
