import { Head, Link, router } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';
import ChannelLogo from '../../Components/ChannelLogo';
import AuthenticatedLayout from '../../Layouts/AuthenticatedLayout';
import { syncCategoryLabel, syncErrorCodeLabel, syncErrorLabel, syncOperationLabel, syncStatusLabel } from '../../lib/syncLabels';

type Group = { operation: string; channel_account_id: string; account_name: string; channel_name: string; channel_code: string; bucket: string; total_count: number; succeeded_count: number; failed_count: number; running_count: number; latest_at: string; latest_error: string | null };
type Detail = { id: string; status: string; attempt: number; error_category: string | null; error_code: string | null; safe_error_message: string | null; created_at: string; finished_at: string | null; can_retry: boolean };
type Props = { groups: { data: Group[]; next_page_url: string | null; prev_page_url: string | null; from: number | null; to: number | null }; details: Detail[]; summary: { events: number; running: number; succeeded: number; failed: number }; filters: { period: string; status: string; operation: string; account: string; detail_operation: string; detail_account: string; detail_bucket: string }; accounts: { id: string; name: string; channel: string }[]; operations: string[] };

export default function Index({ groups, details, summary, filters, accounts, operations }: Props) {
    const [form, setForm] = useState({ period: filters.period, status: filters.status, operation: filters.operation, account: filters.account });
    const submit = (event: FormEvent) => { event.preventDefault(); router.get('/sync', form, { preserveState: true, replace: true }); };
    const groupStatus = (group: Group) => group.failed_count > 0 ? 'failed' : group.running_count > 0 ? 'running' : 'succeeded';
    const bucketValue = (group: Group) => group.bucket.slice(0, 16).replace('T', ' ') + ':00';
    const detailUrl = (group: Group) => `/sync?${new URLSearchParams({ ...form, detail_operation: group.operation, detail_account: group.channel_account_id, detail_bucket: bucketValue(group) })}`;
    return <AuthenticatedLayout><Head title="İşlem Günlüğü" />
        <section className="page-heading"><span className="eyebrow">Operasyon merkezi</span><h1>İşlem Günlüğü</h1><p>Tekil API kayıtları yerine ilişkili görevleri operasyon grupları halinde izleyin; teknik ayrıntıları yalnızca gerektiğinde açın.</p></section>
        <section className="sync-metric-grid"><article className="sync-metric neutral"><span>Teknik kayıt</span><strong>{summary.events}</strong></article><article className="sync-metric warning"><span>Hazır / İşlemde</span><strong>{summary.running}</strong></article><article className="sync-metric success"><span>Tamamlandı</span><strong>{summary.succeeded}</strong></article><article className="sync-metric danger"><span>Hatalı</span><strong>{summary.failed}</strong></article></section>
        <section className="panel sync-filter-panel"><form onSubmit={submit}><label>Dönem<select value={form.period} onChange={event => setForm({ ...form, period: event.target.value })}><option value="1">Bugün</option><option value="7">Son 7 gün</option><option value="30">Son 30 gün</option><option value="90">Son 90 gün</option><option value="all">Tüm zamanlar</option></select></label><label>Durum<select value={form.status} onChange={event => setForm({ ...form, status: event.target.value })}><option value="all">Tüm durumlar</option><option value="running">Devam eden</option><option value="failed">Hatalı</option><option value="succeeded">Tamamlanan</option></select></label><label>Görev<select value={form.operation} onChange={event => setForm({ ...form, operation: event.target.value })}><option value="">Tüm görevler</option>{operations.map(operation => <option value={operation} key={operation}>{syncOperationLabel(operation)}</option>)}</select></label><label>Mağaza<select value={form.account} onChange={event => setForm({ ...form, account: event.target.value })}><option value="">Tüm mağazalar</option>{accounts.map(account => <option value={account.id} key={account.id}>{account.channel} · {account.name}</option>)}</select></label><button className="button">Uygula</button></form></section>
        <section className="panel data-table-card"><div className="data-table-toolbar"><div><strong>Operasyon grupları</strong><span>Aynı dakikadaki benzer görevler tek satırda birleştirilir</span></div><span className="table-hint">Varsayılan görünüm son 7 gündür.</span></div>{groups.data.length ? <div className="sync-group-list">{groups.data.map(group => { const open = filters.detail_operation === group.operation && filters.detail_account === group.channel_account_id && filters.detail_bucket === bucketValue(group); const status = groupStatus(group); return <article className={`sync-group ${open ? 'open' : ''}`} key={`${group.channel_account_id}-${group.operation}-${group.bucket}`}><Link href={open ? `/sync?${new URLSearchParams(form)}` : detailUrl(group)} preserveScroll><span className={`sync-group-mark ${status}`} /><div className="sync-group-title"><strong>{syncOperationLabel(group.operation)}</strong><small>{new Date(group.latest_at).toLocaleString('tr-TR')}</small></div><div className="sync-group-provider"><ChannelLogo code={group.channel_code} name={group.channel_name} size="small" /><span>{group.account_name}</span></div><div className="sync-group-counts"><span>{group.total_count} kayıt</span>{group.succeeded_count > 0 && <b className="success">{group.succeeded_count} başarılı</b>}{group.failed_count > 0 && <b className="danger">{group.failed_count} hatalı</b>}{group.running_count > 0 && <b>{group.running_count} işlemde</b>}</div><span className={`status ${status}`}>{syncStatusLabel(status)}</span><b className="sync-chevron">⌄</b></Link>{open && <div className="sync-group-details">{details.map(detail => <div key={detail.id}><span className={`status ${detail.status}`}>{syncStatusLabel(detail.status)}</span><time>{new Date(detail.created_at).toLocaleString('tr-TR')}</time><span>Deneme {detail.attempt}</span><p>{syncErrorLabel(detail.error_code, detail.safe_error_message) ?? (detail.status === 'succeeded' ? 'İşlem tamamlandı' : 'Sonuç bekleniyor')}{detail.error_category && <small>{syncCategoryLabel(detail.error_category)}{syncErrorCodeLabel(detail.error_code) ? ` · ${syncErrorCodeLabel(detail.error_code)}` : ''}</small>}</p>{detail.can_retry && <button className="button secondary small" onClick={() => router.post(`/sync/${detail.id}/retry`)}>Tekrar dene</button>}</div>)}{group.total_count > 50 && <p className="table-hint">Performans için son 50 teknik kayıt gösteriliyor.</p>}</div>}</article>; })}</div> : <div className="empty-state"><h2>Operasyon bulunamadı</h2><p>Seçilen dönem ve filtrelerde görev grubu bulunmuyor.</p></div>}<div className="pagination"><span>{groups.from ?? 0}-{groups.to ?? 0}</span><nav>{groups.prev_page_url ? <Link href={groups.prev_page_url}>‹ Önceki</Link> : <span>‹ Önceki</span>}{groups.next_page_url ? <Link href={groups.next_page_url}>Sonraki ›</Link> : <span>Sonraki ›</span>}</nav></div></section>
    </AuthenticatedLayout>;
}
