import { Head, router } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';
import ChannelLogo from '../../Components/ChannelLogo';
import AuthenticatedLayout from '../../Layouts/AuthenticatedLayout';

type Props = { filters: { from: string; to: string; currency: string; account: string }; accounts: { id: string; name: string; channel: string }[]; summary: { sales: number; orders: number; items: number; average_order: number; discounts: number; shipping: number }; daily: { date: string; label: string; orders: number; amount: number }[]; byChannel: { account: string; channel: string; code: string; orders: number; amount: number }[]; topProducts: { name: string; variant: string | null; quantity: number; amount: number }[]; statusCounts: { status: string; count: number }[]; lowStock: { product: string; variant: string; warehouse: string; available: number }[]; syncSummary: { total: number; succeeded: number; failed: number; running: number } };
const statusLabels: Record<string, string> = { pending: 'Yeni', confirmed: 'Onaylandı', processing: 'Hazırlanıyor', shipped: 'Kargoya teslim edildi', delivered: 'Teslim edildi', cancelled: 'İptal', returned: 'İade' };

export default function Index({ filters, accounts, summary, daily, byChannel, topProducts, statusCounts, lowStock, syncSummary }: Props) {
    const [form, setForm] = useState(filters);
    const money = (amount: number) => new Intl.NumberFormat('tr-TR', { style: 'currency', currency: filters.currency }).format(amount / 100);
    const maxDaily = Math.max(...daily.map(item => item.amount), 1);
    const submit = (event: FormEvent) => { event.preventDefault(); router.get('/reports', form, { preserveState: true, replace: true }); };
    return <AuthenticatedLayout><Head title="Detaylı Raporlar" />
        <section className="page-heading"><span className="eyebrow">İş zekâsı</span><h1>Detaylı Raporlar</h1><p>Satış, kanal, ürün, stok ve senkronizasyon performansını birlikte değerlendirin.</p></section>
        <section className="panel report-filter-panel"><form onSubmit={submit}><label>Başlangıç<input type="date" value={form.from} onChange={event => setForm({ ...form, from: event.target.value })} /></label><label>Bitiş<input type="date" value={form.to} onChange={event => setForm({ ...form, to: event.target.value })} /></label><label>Para birimi<select value={form.currency} onChange={event => setForm({ ...form, currency: event.target.value })}><option>TRY</option><option>USD</option><option>EUR</option></select></label><label>Mağaza<select value={form.account} onChange={event => setForm({ ...form, account: event.target.value })}><option value="">Tüm mağazalar</option>{accounts.map(account => <option key={account.id} value={account.id}>{account.channel} · {account.name}</option>)}</select></label><button className="button">Raporu getir</button></form></section>
        <section className="metric-grid report-metrics">{[['Toplam satış', money(summary.sales), `${summary.orders} sipariş`], ['Ortalama sepet', money(summary.average_order), `${summary.items} ürün adedi`], ['Toplam indirim', money(summary.discounts), 'Sipariş indirimleri'], ['Kargo geliri', money(summary.shipping), 'Tahsil edilen kargo']].map(([label, value, note]) => <article className="metric-card" key={label}><div><small>{label}</small><strong>{value}</strong><span>{note}</span></div></article>)}</section>
        <section className="panel report-chart"><div className="panel-title"><div><span className="eyebrow">Satış trendi</span><h2>Günlük performans</h2></div></div><div className="report-bars">{daily.map(day => <div className="report-bar" key={day.date} title={`${day.orders} sipariş · ${money(day.amount)}`}><div><span style={{ height: `${Math.max(day.amount / maxDaily * 100, day.amount ? 4 : 1)}%` }} /></div><small>{day.label}</small></div>)}</div></section>
        <section className="report-grid"><article className="panel"><div className="panel-title"><div><span className="eyebrow">Kanallar</span><h2>Kanal performansı</h2></div></div><div className="report-list">{byChannel.map(row => <div key={`${row.code}-${row.account}`}><ChannelLogo code={row.code} name={row.channel} /><span><strong>{row.account}</strong><small>{row.orders} sipariş</small></span><b>{money(row.amount)}</b></div>)}{byChannel.length === 0 && <p>Seçilen aralıkta satış bulunmuyor.</p>}</div></article><article className="panel"><div className="panel-title"><div><span className="eyebrow">Siparişler</span><h2>Durum dağılımı</h2></div></div><div className="status-report-list">{statusCounts.map(row => <div key={row.status}><span>{statusLabels[row.status] ?? row.status}</span><strong>{row.count}</strong><i style={{ width: `${summary.orders ? row.count / summary.orders * 100 : 0}%` }} /></div>)}</div></article></section>
        <section className="report-grid"><article className="panel"><div className="panel-title"><div><span className="eyebrow">Ürünler</span><h2>En çok satanlar</h2></div></div><div className="table-wrap"><table><thead><tr><th>Ürün</th><th>Adet</th><th>Ciro</th></tr></thead><tbody>{topProducts.map((row, index) => <tr key={`${row.name}-${index}`}><td><strong>{row.name}</strong><small>{row.variant}</small></td><td>{row.quantity}</td><td>{money(row.amount)}</td></tr>)}</tbody></table></div></article><article className="panel"><div className="panel-title"><div><span className="eyebrow">Stok riski</span><h2>Düşük stoklar</h2></div></div><div className="table-wrap"><table><thead><tr><th>Ürün</th><th>Depo</th><th>Kalan</th></tr></thead><tbody>{lowStock.map((row, index) => <tr key={`${row.product}-${row.warehouse}-${index}`}><td><strong>{row.product}</strong><small>{row.variant}</small></td><td>{row.warehouse}</td><td><strong className={row.available <= 0 ? 'stock-danger' : 'stock-warning'}>{row.available}</strong></td></tr>)}</tbody></table></div></article></section>
        <section className="panel sync-report"><div className="panel-title"><div><span className="eyebrow">Entegrasyon sağlığı</span><h2>Senkronizasyon özeti</h2></div></div><div>{[['Toplam işlem', syncSummary.total], ['Başarılı', syncSummary.succeeded], ['Devam eden', syncSummary.running], ['Başarısız', syncSummary.failed]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div></section>
    </AuthenticatedLayout>;
}
