server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location /storage/ {
        alias /var/www/html/storage/app/public/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        set $php_fpm app:9000;
        fastcgi_pass $php_fpm;
        fastcgi_read_timeout 60s;
    }

    location ~ /\.ht { deny all; }
}
