import { Link, router, useForm } from '@inertiajs/react';
import { useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import ChannelLogo from './ChannelLogo';

type Item = { id: string; name: string; slug: string; description?: string | null; status: string; products_count: number; parent_id?: string | null; parent?: { name: string } | null };
type Page = { data: Item[]; links: { url: string | null; label: string; active: boolean }[]; from?: number | null; to?: number | null; total?: number };
type Account = { id: string; name: string; channel: { name: string; code: string } };
type Mapping = { id: string; reference_id: string; external_id: string; external_name: string; account: Account };
type Props = { title: string; singular: string; endpoint: string; items: Page; canManage: boolean; parentOptions?: { id: string; name: string }[]; channelAccounts?: Account[]; mappings?: Mapping[] };

export default function CatalogReferencePage({ title, singular, endpoint, items, canManage, parentOptions = [], channelAccounts = [], mappings = [] }: Props) {
    const referenceType = endpoint === 'categories' ? 'category' : 'brand';
    const [editing, setEditing] = useState<Item | null>(null);
    const [modalOpen, setModalOpen] = useState(false);
    const [matching, setMatching] = useState<Item | null>(null);
    const [lookup, setLookup] = useState<{ id: string; name: string }[]>([]);
    const [lookupBusy, setLookupBusy] = useState(false);
    const form = useForm({ name: '', slug: '', description: '', status: 'active', ...(endpoint === 'categories' ? { parent_id: '' } : {}) });
    const matchForm = useForm({ channel_account_id: channelAccounts[0]?.id ?? '', reference_type: referenceType, reference_id: '', external_id: '', external_name: '' });
    const groupedMappings = useMemo(() => mappings.reduce<Record<string, Mapping[]>>((result, mapping) => ({ ...result, [mapping.reference_id]: [...(result[mapping.reference_id] ?? []), mapping] }), {}), [mappings]);
    const slugify = (value: string) => value.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/ı/g, 'i').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    const close = () => { setModalOpen(false); setEditing(null); form.reset(); form.clearErrors(); };
    const create = () => { close(); setModalOpen(true); };
    const edit = (item: Item) => { setEditing(item); form.setData({ ...form.data, name: item.name, slug: item.slug, description: item.description ?? '', status: item.status, ...(endpoint === 'categories' ? { parent_id: item.parent_id ?? '' } : {}) }); setModalOpen(true); };
    const submit = (event: FormEvent) => { event.preventDefault(); const options = { preserveScroll: true, onSuccess: close }; editing ? form.put(`/${endpoint}/${editing.id}`, options) : form.post(`/${endpoint}`, options); };
    const openMatch = (item: Item) => { setMatching(item); setLookup([]); matchForm.setData({ channel_account_id: channelAccounts[0]?.id ?? '', reference_type: referenceType, reference_id: item.id, external_id: '', external_name: '' }); };
    const selectedAccount = channelAccounts.find(account => account.id === matchForm.data.channel_account_id);
    const lookupMarketplace = async () => {
        if (!selectedAccount || selectedAccount.channel.code !== 'trendyol' || !matching) return;
        setLookupBusy(true);
        try {
            const url = referenceType === 'category' ? `/channels/accounts/${selectedAccount.id}/trendyol/categories` : `/channels/accounts/${selectedAccount.id}/trendyol/brands?name=${encodeURIComponent(matching.name)}`;
            const response = await fetch(url, { headers: { Accept: 'application/json' } });
            const body = await response.json();
            setLookup(body.categories ?? body.brands ?? []);
        } finally { setLookupBusy(false); }
    };
    const saveMatch = (event: FormEvent) => { event.preventDefault(); matchForm.post('/channel-reference-mappings', { preserveScroll: true, onSuccess: () => setMatching(null) }); };

    return <>
        <section className="page-heading heading-actions"><div><span className="eyebrow">Katalog sözlüğü</span><h1>{title}</h1><p>Merkezi katalog değerlerini ve pazaryeri karşılıklarını tek ekrandan yönetin.</p></div>{canManage && <button className="button" onClick={create}>+ Yeni {singular.toLocaleLowerCase('tr-TR')}</button>}</section>
        <section className="panel data-table-card"><div className="data-table-toolbar"><div><strong>{title}</strong><span>{items.total ?? items.data.length} kayıt</span></div><div className="table-hint">Pazaryeri sütunundaki <b>+</b> ile yeni eşleştirme ekleyin.</div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Ad</th><th>Kısa ad</th>{endpoint === 'categories' && <th>Üst kategori</th>}<th>Ürün</th><th>Pazaryeri</th><th>Durum</th>{canManage && <th>İşlem</th>}</tr></thead><tbody>{items.data.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td><code>{item.slug}</code></td>{endpoint === 'categories' && <td>{item.parent?.name ?? '—'}</td>}<td>{item.products_count}</td><td><div className="mapping-cell">{(groupedMappings[item.id] ?? []).map(mapping => <span className="logo-mapping" title={`${mapping.account.channel.name} · ${mapping.external_name} · ${mapping.external_id}`} key={mapping.id}><ChannelLogo code={mapping.account.channel.code} name={mapping.account.channel.name} size="small" /><small>{mapping.external_name}</small></span>)}{canManage && <button className="mapping-add" type="button" onClick={() => openMatch(item)} aria-label={`${item.name} için eşleştirme ekle`}>+</button>}</div></td><td><span className={`status ${item.status}`}>{item.status === 'active' ? 'Aktif' : item.status === 'draft' ? 'Taslak' : 'Arşiv'}</span></td>{canManage && <td><div className="row-actions"><button onClick={() => edit(item)}>Düzenle</button><button className="danger-link" onClick={() => confirm(`${item.name} silinsin mi?`) && router.delete(`/${endpoint}/${item.id}`)}>Sil</button></div></td>}</tr>)}</tbody></table>{items.data.length === 0 && <div className="empty-state"><h3>Henüz kayıt yok</h3><p>İlk {singular.toLocaleLowerCase('tr-TR')} kaydınızı oluşturun.</p></div>}</div>{items.links?.length > 3 && <div className="pagination"><span>{items.from}-{items.to} / {items.total}</span><nav>{items.links.map((link, index) => link.url ? <Link className={link.active ? 'active' : ''} href={link.url} key={index} dangerouslySetInnerHTML={{ __html: link.label }} /> : <span key={index} dangerouslySetInnerHTML={{ __html: link.label }} />)}</nav></div>}</section>

        {canManage && modalOpen && <div className="modal-layer"><button aria-label="Kapat" className="modal-backdrop" onClick={close} /><section className="modal-card" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Katalog yönetimi</span><h2>{editing ? `${singular} düzenle` : `Yeni ${singular.toLocaleLowerCase('tr-TR')}`}</h2></div><button className="modal-close" onClick={close}>×</button></header><form className="form-panel" onSubmit={submit}><div className="form-row"><label>Ad<input autoFocus value={form.data.name} onChange={event => { form.setData('name', event.target.value); if (!editing) form.setData('slug', slugify(event.target.value)); }} /></label><label>Kısa ad<input value={form.data.slug} onChange={event => form.setData('slug', event.target.value)} /></label></div>{'parent_id' in form.data && <label>Üst kategori<select value={form.data.parent_id} onChange={event => form.setData('parent_id', event.target.value)}><option value="">Ana kategori</option>{parentOptions.filter(option => option.id !== editing?.id).map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>}<label>Açıklama<textarea rows={4} value={form.data.description} onChange={event => form.setData('description', event.target.value)} /></label><label>Durum<select value={form.data.status} onChange={event => form.setData('status', event.target.value)}><option value="active">Aktif</option><option value="draft">Taslak</option><option value="archived">Arşiv</option></select></label>{Object.values(form.errors).map(error => <span className="error" key={error}>{error}</span>)}<footer><button className="button secondary" onClick={close} type="button">Vazgeç</button><button className="button" disabled={form.processing}>{editing ? 'Değişiklikleri kaydet' : 'Oluştur'}</button></footer></form></section></div>}

        {matching && <div className="modal-layer"><button aria-label="Kapat" className="modal-backdrop" onClick={() => setMatching(null)} /><section className="modal-card mapping-modal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Pazaryeri eşleştirme</span><h2>{matching.name}</h2><p>Merkezi {singular.toLocaleLowerCase('tr-TR')} değerinin pazaryerindeki karşılığını seçin.</p></div><button className="modal-close" onClick={() => setMatching(null)}>×</button></header><form className="form-panel" onSubmit={saveMatch}><label>Pazaryeri hesabı<select value={matchForm.data.channel_account_id} onChange={event => { matchForm.setData('channel_account_id', event.target.value); setLookup([]); }}><option value="">Hesap seçin</option>{channelAccounts.map(account => <option key={account.id} value={account.id}>{account.channel.name} · {account.name}</option>)}</select></label>{selectedAccount?.channel.code === 'trendyol' && <button className="button secondary" type="button" disabled={lookupBusy} onClick={lookupMarketplace}>{lookupBusy ? 'Pazaryeri aranıyor…' : `Trendyol'da “${matching.name}” ara`}</button>}{lookup.length > 0 && <div className="lookup-results">{lookup.map(option => <button type="button" key={option.id} onClick={() => matchForm.setData(data => ({ ...data, external_id: String(option.id), external_name: option.name }))}><strong>{option.name}</strong><small>ID: {option.id}</small></button>)}</div>}<div className="form-row"><label>Pazaryeri ID<input value={matchForm.data.external_id} onChange={event => matchForm.setData('external_id', event.target.value)} /></label><label>Pazaryeri adı<input value={matchForm.data.external_name} onChange={event => matchForm.setData('external_name', event.target.value)} /></label></div>{Object.values(matchForm.errors).map(error => <span className="error" key={error}>{error}</span>)}<footer><button className="button secondary" type="button" onClick={() => setMatching(null)}>Vazgeç</button><button className="button" disabled={matchForm.processing || !matchForm.data.channel_account_id}>Eşleştirmeyi kaydet</button></footer></form></section></div>}
    </>;
}
