import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';
import AuthenticatedLayout from '../../Layouts/AuthenticatedLayout';
import ChannelLogo from '../../Components/ChannelLogo';
import type { SharedProps } from '../../types';

type Variant = { id: string; name: string; sku: string | null; barcode: string | null };
type Row = { id: string; name: string; brand: string | null; category: string | null; status: string; vat_rate: number; variants_count: number; product_type: string; sku: string | null; price: string | null; currency: string | null; available: number; image_url: string | null; channels: { name: string; code: string }[]; variants: Variant[] };
type Account = { id: string; name: string; channel: { name: string; code: string } };
type TrendyolTemplate = { id: string; name: string; category_id: string | null; category: string | null };
type RemoteProduct = { external_product_id: string; external_variant_id: string | null; name: string; sku: string | null; barcode: string | null; image_url: string | null; status: string; selectable: boolean; note: string | null; already_mapped: boolean };
type PageLink = { url: string | null; label: string; active: boolean };
type Props = { products: { data: Row[]; links: PageLink[]; from: number | null; to: number | null; total: number }; filters: { search: string }; canCreate: boolean; channelAccounts: Account[]; trendyolTemplates: TrendyolTemplate[] };
const durum = (value: string) => ({ draft: 'Taslak', active: 'Aktif', archived: 'Arşivlendi' }[value] ?? value);

export default function Index({ products, filters, canCreate, channelAccounts, trendyolTemplates }: Props) {
    const bulkResult = usePage<SharedProps>().props.flash.bulkPublishResult;
    const [search, setSearch] = useState(filters.search);
    const [matching, setMatching] = useState<Row | null>(null);
    const [stage, setStage] = useState<'account' | 'products'>('account');
    const [remoteSearch, setRemoteSearch] = useState('');
    const [remoteProducts, setRemoteProducts] = useState<RemoteProduct[]>([]);
    const [loading, setLoading] = useState(false);
    const [lookupError, setLookupError] = useState('');
    const [accountId, setAccountId] = useState('');
    const [selectedProducts, setSelectedProducts] = useState<string[]>([]);
    const [selectAllMatching, setSelectAllMatching] = useState(false);
    const [bulkOpen, setBulkOpen] = useState(false);
    const bulkForm = useForm({ product_ids: [] as string[], channel_account_ids: [] as string[], trendyol_template_id: '', select_all: false, search: filters.search });
    const matchForm = useForm({ channel_account_id: '', product_id: '', product_variant_id: '', external_product_id: '', external_variant_id: '', external_sku: '', external_barcode: '' });
    const account = channelAccounts.find(item => item.id === accountId);
    const submit = (event: FormEvent) => { event.preventDefault(); router.get('/products', { search }, { preserveState: true, replace: true }); };
    const close = () => { setMatching(null); setStage('account'); setRemoteProducts([]); setLookupError(''); };
    const openMatch = (product: Row) => { setMatching(product); setAccountId(''); setStage('account'); setRemoteSearch(product.sku ?? product.name); matchForm.clearErrors(); };
    const loadProducts = async (selectedAccount = accountId, query = remoteSearch) => {
        if (!selectedAccount) return;
        setLoading(true); setLookupError('');
        try {
            const response = await fetch(`/channels/accounts/${selectedAccount}/marketplace-products?search=${encodeURIComponent(query)}`, { headers: { Accept: 'application/json' } });
            const data = await response.json();
            if (!response.ok) throw new Error(data.message ?? 'Pazaryeri ürünleri yüklenemedi.');
            setRemoteProducts(data.products ?? []); setStage('products');
        } catch (error) { setLookupError(error instanceof Error ? error.message : 'Pazaryeri ürünleri yüklenemedi.'); }
        finally { setLoading(false); }
    };
    const selectRemote = (remote: RemoteProduct) => {
        if (!matching || !remote.selectable || remote.already_mapped) return;
        matchForm.setData({ channel_account_id: accountId, product_id: matching.id, product_variant_id: matching.variants[0]?.id ?? '', external_product_id: remote.external_product_id, external_variant_id: remote.external_variant_id ?? '', external_sku: remote.sku ?? '', external_barcode: remote.barcode ?? '' });
        matchForm.post('/channel-listing-mappings', { preserveScroll: true, onSuccess: close });
    };
    const publish = () => {
        if (!matching || !account) return;
        if (account.channel.code === 'woocommerce') router.post(`/products/${matching.id}/woocommerce/${account.id}`, {}, { onSuccess: close });
        else router.visit(`/products/${matching.id}?publish=${account.id}`);
    };
    const toggleProduct = (id: string) => { setSelectAllMatching(false); setSelectedProducts(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]); };
    const togglePage = () => { setSelectAllMatching(false); setSelectedProducts(selectedProducts.length === products.data.length ? [] : products.data.map(product => product.id)); };
    const selectEveryMatchingProduct = () => { setSelectAllMatching(true); setSelectedProducts(products.data.map(product => product.id)); };
    const openBulk = () => { bulkForm.setData({ product_ids: selectedProducts, channel_account_ids: [], trendyol_template_id: '', select_all: selectAllMatching, search: filters.search }); setBulkOpen(true); };
    const toggleBulkAccount = (id: string) => bulkForm.setData('channel_account_ids', bulkForm.data.channel_account_ids.includes(id) ? bulkForm.data.channel_account_ids.filter(item => item !== id) : [...bulkForm.data.channel_account_ids, id]);
    const submitBulk = () => bulkForm.post('/products/bulk-publish', { preserveScroll: true, onSuccess: () => { setBulkOpen(false); setSelectedProducts([]); setSelectAllMatching(false); } });

    return <AuthenticatedLayout><Head title="Ürünler" />
        <section className="page-heading heading-actions"><div><span className="eyebrow">Merkezi katalog</span><h1>Ürünler</h1><p>Ürün, stok ve pazaryeri eşleştirmelerini tek listeden yönetin.</p></div>{canCreate && <Link className="button" href="/products/create">+ Yeni ürün</Link>}</section>
        {bulkResult && <section className="panel"><strong>Toplu yayın sonucu</strong><div className="setup-summary-grid"><article><span>Kuyrukta</span><strong>{bulkResult.queued}</strong></article><article><span>Zaten bağlı</span><strong>{bulkResult.already_linked}</strong></article><article><span>Engelli</span><strong>{bulkResult.blocked}</strong></article><article><span>Başarılı</span><strong>{bulkResult.succeeded}</strong></article><article><span>Başarısız</span><strong>{bulkResult.failed}</strong></article></div></section>}
        <section className="panel data-table-card"><div className="data-table-toolbar"><div><strong>Ürün kataloğu</strong><span>{products.total} kayıt</span></div><div className="catalog-toolbar-actions">{selectedProducts.length === products.data.length && products.total > products.data.length && !selectAllMatching && <button className="button secondary" type="button" onClick={selectEveryMatchingProduct}>Filtredeki {products.total} ürünün tümünü seç</button>}{selectedProducts.length > 0 && <button className="button" type="button" onClick={openBulk}>{selectAllMatching ? products.total : selectedProducts.length} ürünü pazaryerlerine gönder</button>}<form className="search-form" onSubmit={submit}><input aria-label="Ürün ara" placeholder="Ad, marka, SKU veya barkod ara" value={search} onChange={e => setSearch(e.target.value)} /><button className="button secondary">Ara</button></form></div></div>
            {products.data.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th className="selection-column"><input type="checkbox" aria-label="Sayfadaki tüm ürünleri seç" checked={selectedProducts.length === products.data.length && products.data.length > 0} onChange={togglePage} /></th><th>Ürün</th><th>Stok kodu</th><th>KDV</th><th>Stok</th><th>Satış fiyatı</th><th>Marka / Kategori</th><th>Tip</th><th>Pazaryeri</th><th>Durum</th><th /></tr></thead><tbody>{products.data.map(product => <tr className={selectedProducts.includes(product.id) ? 'selected-row' : ''} key={product.id}><td className="selection-column"><input type="checkbox" aria-label={`${product.name} ürününü seç`} checked={selectedProducts.includes(product.id)} onChange={() => toggleProduct(product.id)} /></td><td><div className="product-cell">{product.image_url ? <img src={product.image_url} alt="" /> : <span className="product-thumb-placeholder">◇</span>}<div><strong>{product.name}</strong><small>{product.variants_count} varyant</small></div></div></td><td>{product.sku ?? '—'}</td><td>%{product.vat_rate}</td><td><strong className={product.available <= 0 ? 'stock-danger' : 'stock-ok'}>{product.available}</strong></td><td>{product.price ? `${product.price} ${product.currency}` : '—'}</td><td>{product.brand ?? 'Marka yok'}<small>{product.category ?? 'Kategori yok'}</small></td><td>{product.product_type}</td><td><div className="mapping-cell">{product.channels.map(channel => <ChannelLogo code={channel.code} name={channel.name} size="small" key={channel.code} />)}<button className="mapping-add" onClick={() => openMatch(product)} title="Pazaryeri ürünüyle eşleştir">+</button></div></td><td><span className={`status ${product.status}`}>{durum(product.status)}</span></td><td><Link href={`/products/${product.id}`}>Görüntüle</Link></td></tr>)}</tbody></table></div> : <div className="empty-state"><h2>Ürün bulunamadı</h2><p>İlk ürününüzü oluşturun veya arama kriterini değiştirin.</p></div>}
            {products.total > 0 && <div className="pagination"><span>{products.from}-{products.to} / {products.total}</span><nav>{products.links.map((link, index) => link.url ? <Link className={link.active ? 'active' : ''} href={link.url} key={index} dangerouslySetInnerHTML={{ __html: link.label }} /> : <span key={index} dangerouslySetInnerHTML={{ __html: link.label }} />)}</nav></div>}</section>

        {matching && <div className="modal-layer"><button className="modal-backdrop" aria-label="Kapat" onClick={close} /><section className="modal-card marketplace-product-modal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Pazaryeri eşleştirme</span><h2>{matching.name}</h2><p>Kimlik bilgilerini sistem arka planda yönetecek; yalnızca mağaza ve ürünü seçin.</p></div><button className="modal-close" onClick={close}>×</button></header>
            {stage === 'account' && <div className="marketplace-modal-body"><h3>Hangi mağazada işlem yapacaksınız?</h3><div className="marketplace-account-grid">{channelAccounts.map(item => <button type="button" className={accountId === item.id ? 'selected' : ''} key={item.id} onClick={() => setAccountId(item.id)}><ChannelLogo code={item.channel.code} name={item.channel.name} size="large" /><span><strong>{item.channel.name}</strong><small>{item.name}</small></span><b>›</b></button>)}</div>{channelAccounts.length === 0 && <div className="empty-state"><h3>Aktif entegrasyon yok</h3><Link className="button" href="/channels">Entegrasyon ekle</Link></div>}{lookupError && <span className="error">{lookupError}</span>}<footer><button className="button secondary" onClick={close}>Vazgeç</button><button className="button" disabled={!accountId || loading} onClick={() => void loadProducts()}>{loading ? 'Yükleniyor…' : 'Ürünleri göster'}</button></footer></div>}
            {stage === 'products' && <div className="marketplace-modal-body"><div className="marketplace-list-heading"><div><ChannelLogo code={account?.channel.code ?? ''} name={account?.channel.name ?? ''} size="small" /><span><strong>{account?.name}</strong><small>Pazaryeri kataloğu</small></span></div><button className="button" onClick={publish}>+ Pazaryerine ürün ekle</button></div><form className="search-form marketplace-search" onSubmit={e => { e.preventDefault(); void loadProducts(); }}><input value={remoteSearch} onChange={e => setRemoteSearch(e.target.value)} placeholder="Ürün adı, SKU veya barkod ara" /><button className="button secondary" disabled={loading}>Ara</button></form>{lookupError && <span className="error">{lookupError}</span>}<div className="remote-product-list">{remoteProducts.map(remote => <button type="button" key={`${remote.external_product_id}-${remote.external_variant_id ?? ''}`} disabled={!remote.selectable || remote.already_mapped || matchForm.processing} onClick={() => selectRemote(remote)}>{remote.image_url ? <img src={remote.image_url} alt="" /> : <span className="product-thumb-placeholder">◇</span>}<span><strong>{remote.name}</strong><small>{[remote.sku && `SKU: ${remote.sku}`, remote.barcode && `Barkod: ${remote.barcode}`].filter(Boolean).join(' · ') || 'Kod bilgisi yok'}</small>{remote.note && <em>{remote.note}</em>}</span><b>{remote.already_mapped ? 'Eşleşmiş' : remote.selectable ? 'Seç' : '—'}</b></button>)}</div>{!loading && remoteProducts.length === 0 && <div className="empty-state compact"><h3>Ürün bulunamadı</h3><p>Aramayı değiştirin veya pazaryerine yeni ürün ekleyin.</p></div>}<footer><button className="button secondary" onClick={() => setStage('account')}>Geri</button></footer></div>}
        </section></div>}
        {bulkOpen && <div className="modal-layer"><button className="modal-backdrop" aria-label="Kapat" onClick={() => setBulkOpen(false)} /><section className="modal-card bulk-publish-modal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Toplu pazaryeri yayını</span><h2>{selectedProducts.length} ürünü gönder</h2><p>Ürünleri göndermek istediğiniz bir veya daha fazla aktif mağazayı seçin.</p></div><button className="modal-close" onClick={() => setBulkOpen(false)}>×</button></header><div className="marketplace-modal-body"><div className="marketplace-account-grid">{channelAccounts.map(item => { const selected = bulkForm.data.channel_account_ids.includes(item.id); return <button type="button" className={selected ? 'selected' : ''} key={item.id} onClick={() => toggleBulkAccount(item.id)}><ChannelLogo code={item.channel.code} name={item.channel.name} size="large" /><span><strong>{item.channel.name}</strong><small>{item.name}</small></span><b>{selected ? '✓' : '+'}</b></button>; })}</div>{channelAccounts.some(item => item.channel.code === 'trendyol' && bulkForm.data.channel_account_ids.includes(item.id)) && <label>Trendyol yayın şablonu<select value={bulkForm.data.trendyol_template_id} onChange={event => bulkForm.setData('trendyol_template_id', event.target.value)}><option value="">Şablon seçin</option>{trendyolTemplates.map(template => <option key={template.id} value={template.id}>{template.name}{template.category ? ` · ${template.category}` : ''}</option>)}</select><small>Uyumsuz veya zorunlu bilgisi eksik ürünler engelli olarak raporlanır.</small></label>}<div className="bulk-publish-note"><strong>Nasıl çalışır?</strong><p>Hazır ürünler kuyruğa alınır; bağlı ürünler tekrarlanmaz. Eksik SKU, barkod, TRY fiyatı, HTTPS görseli veya şablon uyumsuzluğu diğer ürünleri durdurmaz.</p></div>{Object.values(bulkForm.errors).map(error => <span className="error" key={error}>{error}</span>)}<footer><button className="button secondary" type="button" onClick={() => setBulkOpen(false)}>Vazgeç</button><button className="button" type="button" disabled={bulkForm.processing || bulkForm.data.channel_account_ids.length === 0} onClick={submitBulk}>{bulkForm.processing ? 'Kuyruğa alınıyor…' : 'Seçili mağazalara gönder'}</button></footer></div></section></div>}
    </AuthenticatedLayout>;
}
