import { Head, router, useForm } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';
import AuthenticatedLayout from '../../Layouts/AuthenticatedLayout';

type Definition = { id: string; name: string; values: string[]; status: string };

export default function Index({ definitions, canManage }: { definitions: { data: Definition[] }; canManage: boolean }) {
    const [drawerOpen, setDrawerOpen] = useState(false);
    const [editing, setEditing] = useState<Definition | null>(null);
    const form = useForm({ name: '', values: '', status: 'active' });
    const submit = (event: FormEvent) => { event.preventDefault(); const payload = { ...form.data, values: form.data.values }; editing ? router.put(`/variant-definitions/${editing.id}`, payload, { onSuccess: reset }) : router.post('/variant-definitions', payload, { onSuccess: reset }); };
    const reset = () => { setEditing(null); setDrawerOpen(false); form.reset(); };
    const create = () => { setEditing(null); form.reset(); setDrawerOpen(true); };
    const edit = (item: Definition) => { setEditing(item); form.setData({ name: item.name, values: item.values.join(', '), status: item.status }); setDrawerOpen(true); };

    return <AuthenticatedLayout><Head title="Varyantlar" /><section className="page-heading heading-actions"><div><span className="eyebrow">Katalog</span><h1>Varyantlar</h1><p>Renk, beden, materyal gibi varyant özelliklerini ve kullanılabilir değerlerini yönetin.</p></div>{canManage && <button className="button" onClick={create}>Yeni varyant ekle</button>}</section><section className="panel"><div className="table-wrap"><table><thead><tr><th>Varyant</th><th>Değerler</th><th>Durum</th>{canManage && <th>İşlem</th>}</tr></thead><tbody>{definitions.data.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td><div className="chip-list">{item.values.map((value) => <span key={value}>{value}</span>)}</div></td><td><span className="status">{item.status}</span></td>{canManage && <td><div className="form-actions"><button className="button secondary small" onClick={() => edit(item)}>Düzenle</button><button className="danger-link" onClick={() => confirm('Varyant silinsin mi?') && router.delete(`/variant-definitions/${item.id}`)}>Sil</button></div></td>}</tr>)}</tbody></table>{definitions.data.length === 0 && <div className="empty-state"><h3>Henüz varyant yok</h3><p>Şablonlarda kullanmak için ilk varyantınızı ekleyin.</p></div>}</div></section>{drawerOpen && <><button aria-label="Paneli kapat" className="drawer-backdrop" onClick={reset} /><aside className="form-drawer"><header><div><small>Katalog</small><h2>{editing ? 'Varyantı düzenle' : 'Yeni varyant ekle'}</h2></div><button aria-label="Kapat" onClick={reset} type="button">×</button></header><form className="form-panel" onSubmit={submit}><label>Varyant adı<input autoFocus placeholder="Örn. Renk" value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} /></label><label>Değerler<input placeholder="Siyah, Beyaz, Kırmızı" value={form.data.values} onChange={(event) => form.setData('values', event.target.value)} /><small>Değerleri virgülle ayırın.</small></label><label>Durum<select value={form.data.status} onChange={(event) => form.setData('status', event.target.value)}><option value="active">Aktif</option><option value="draft">Taslak</option><option value="archived">Arşiv</option></select></label>{Object.values(form.errors).map((error) => <span className="error" key={error}>{error}</span>)}<footer><button className="button secondary" onClick={reset} type="button">Vazgeç</button><button className="button" disabled={form.processing}>Kaydet</button></footer></form></aside></>}</AuthenticatedLayout>;
}
