import { Head, router, useForm } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';
import AuthenticatedLayout from '../../Layouts/AuthenticatedLayout';

type Tab = 'profile' | 'company' | 'members';
type Tenant = { id:string; name:string; slug:string; status:string; subscription_plan:string; subscription_status:string; legal_title:string|null; contact_first_name:string|null; contact_last_name:string|null; mobile_phone:string|null; company_email:string|null; website:string|null; company_phone:string|null; province:string|null; district:string|null; address:string|null; company_type:string|null; tax_office:string|null; national_id:string|null };
type Props = { tenant:Tenant; profile:{name:string;email:string;registered_at:string}; trial:{ends_at:string;total_days:number;remaining_days:number;remaining_percent:number}; members:Array<{id:string;name:string;email:string;role:string}>; canUpdate:boolean; canManageMembers:boolean; currentRole:string };
const roles:Record<string,string> = { owner:'Firma sahibi', admin:'Yönetici', operator:'Operatör', viewer:'Görüntüleyici' };

export default function Organization({tenant,profile,trial,members,canUpdate,canManageMembers,currentRole}:Props) {
 const [tab,setTab]=useState<Tab>('profile');
 const profileForm=useForm({name:profile.name,email:profile.email});
 const companyForm=useForm({name:tenant.name,legal_title:tenant.legal_title??'',contact_first_name:tenant.contact_first_name??'',contact_last_name:tenant.contact_last_name??'',mobile_phone:tenant.mobile_phone??'',company_email:tenant.company_email??profile.email,website:tenant.website??'',company_phone:tenant.company_phone??'',province:tenant.province??'',district:tenant.district??'',address:tenant.address??'',company_type:tenant.company_type??'individual',tax_office:tenant.tax_office??'',national_id:tenant.national_id??''});
 const memberForm=useForm({email:'',role:'viewer'});
 const saveProfile=(e:FormEvent)=>{e.preventDefault();profileForm.put('/settings/profile',{preserveScroll:true})};
 const saveCompany=(e:FormEvent)=>{e.preventDefault();companyForm.put(`/settings/organizations/${tenant.id}`,{preserveScroll:true})};
 const addMember=(e:FormEvent)=>{e.preventDefault();memberForm.post(`/settings/organizations/${tenant.id}/members`,{preserveScroll:true,onSuccess:()=>memberForm.reset('email')})};
 const manageable=(role:string)=>currentRole==='owner'||!['owner','admin'].includes(role);
 return <AuthenticatedLayout><Head title="Ayarlar"/><section className="page-heading"><span className="eyebrow">Hesap ve firma yönetimi</span><h1>Ayarlar</h1><p>Profilinizi, firma bilgilerinizi ve panel kullanıcılarını yönetin.</p></section>
 <nav className="settings-tabs" aria-label="Ayar bölümleri"><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>Profil Ayarları</button><button className={tab==='company'?'active':''} onClick={()=>setTab('company')}>Firma Ayarları</button><button className={tab==='members'?'active':''} onClick={()=>setTab('members')}>Kullanıcı Ekleme</button></nav>
 {tab==='profile'&&<div className="settings-profile-grid"><form className="panel form-panel" onSubmit={saveProfile}><div className="panel-title"><div><span className="eyebrow">Kişisel bilgiler</span><h2>Profil Ayarları</h2></div></div><div className="form-row"><label>Ad Soyad<input value={profileForm.data.name} onChange={e=>profileForm.setData('name',e.target.value)}/></label><label>E-Posta<input type="email" value={profileForm.data.email} onChange={e=>profileForm.setData('email',e.target.value)}/></label></div><div className="profile-facts"><div><span>Kayıt Tarihi</span><strong>{profile.registered_at}</strong></div><div><span>Demo Bitiş Tarihi</span><strong>{trial.ends_at}</strong></div></div>{Object.values(profileForm.errors).map(x=><span className="error" key={x}>{x}</span>)}<footer><button className="button" disabled={profileForm.processing}>Profili Kaydet</button></footer></form><aside className="settings-side-stack"><section className="panel trial-card"><span className="eyebrow">Demo Süresi</span><div className="trial-value"><strong>{trial.remaining_days}</strong><span>Kalan: {trial.remaining_days} Gün</span></div><div className="trial-progress"><i style={{width:`${Math.min(100,trial.remaining_percent)}%`}}/></div><div className="trial-meta"><span>{trial.total_days} Gün</span><strong>%{trial.remaining_percent}</strong></div></section><section className="panel addon-card"><div className="addon-icon">₺</div><div><h3>E-Fatura</h3><p>Faturalarınızı kolayca yönetin</p></div><span className="status">Yakında</span></section><section className="panel addon-empty"><span className="eyebrow">Ek Paketler</span><h3>Özelleştirilmiş çözümler</h3><strong>Ekstra Paketiniz Bulunmuyor</strong><p>Panelinize yeni özellikler eklemek için ekstra paket satın alın.</p></section></aside></div>}
 {tab==='company'&&<form className="panel form-panel company-settings-form" onSubmit={saveCompany}><div className="panel-title"><div><span className="eyebrow">Kurumsal bilgiler</span><h2>Firma Ayarları</h2><p>Fatura ve firma iletişim bilgileriniz.</p></div></div><label>Ticari Ünvan<input disabled={!canUpdate} value={companyForm.data.legal_title} onChange={e=>companyForm.setData('legal_title',e.target.value)}/></label><div className="form-row"><label>Ad<input disabled={!canUpdate} value={companyForm.data.contact_first_name} onChange={e=>companyForm.setData('contact_first_name',e.target.value)}/></label><label>Soyad<input disabled={!canUpdate} value={companyForm.data.contact_last_name} onChange={e=>companyForm.setData('contact_last_name',e.target.value)}/></label></div><div className="form-row"><label>Cep Telefonu<input disabled={!canUpdate} placeholder="(5XX) XXX-XXXX" value={companyForm.data.mobile_phone} onChange={e=>companyForm.setData('mobile_phone',e.target.value)}/></label><label>E-Posta<input disabled={!canUpdate} type="email" value={companyForm.data.company_email} onChange={e=>companyForm.setData('company_email',e.target.value)}/></label></div><div className="form-row"><label>Web Sitenizin Adresi<input disabled={!canUpdate} placeholder="example.com" value={companyForm.data.website} onChange={e=>companyForm.setData('website',e.target.value)}/></label><label>Şirket Telefonu<input disabled={!canUpdate} placeholder="(XXX) XXX-XXXX" value={companyForm.data.company_phone} onChange={e=>companyForm.setData('company_phone',e.target.value)}/></label></div><div className="form-row"><label>İl<input disabled={!canUpdate} value={companyForm.data.province} onChange={e=>companyForm.setData('province',e.target.value)}/></label><label>İlçe<input disabled={!canUpdate} value={companyForm.data.district} onChange={e=>companyForm.setData('district',e.target.value)}/></label></div><label>Adres<textarea disabled={!canUpdate} rows={4} value={companyForm.data.address} onChange={e=>companyForm.setData('address',e.target.value)}/></label><div className="form-row"><label>Firma Tipi<select disabled={!canUpdate} value={companyForm.data.company_type} onChange={e=>companyForm.setData('company_type',e.target.value)}><option value="individual">Şahıs</option><option value="corporate">Sermaye Şirketi</option></select></label><label>Vergi Dairesi<input disabled={!canUpdate} value={companyForm.data.tax_office} onChange={e=>companyForm.setData('tax_office',e.target.value)}/></label></div>{companyForm.data.company_type==='individual'&&<label>TC Kimlik No<input disabled={!canUpdate} inputMode="numeric" maxLength={11} value={companyForm.data.national_id} onChange={e=>companyForm.setData('national_id',e.target.value.replace(/\D/g,''))}/></label>}{Object.values(companyForm.errors).map(x=><span className="error" key={x}>{x}</span>)}{canUpdate&&<footer><button className="button" disabled={companyForm.processing}>Firma Bilgilerini Kaydet</button></footer>}</form>}
 {tab==='members'&&<section className="panel member-settings-panel"><div className="panel-title"><div><span className="eyebrow">Ekip yönetimi</span><h2>Kullanıcı Ekleme</h2><p>Firma hesabına erişebilecek kullanıcıları ve yetkilerini yönetin.</p></div><span className="status">{members.length} kullanıcı</span></div>{canManageMembers&&<form className="member-form" onSubmit={addMember}><label>E-Posta<input type="email" value={memberForm.data.email} onChange={e=>memberForm.setData('email',e.target.value)}/></label><label>Yetki<select value={memberForm.data.role} onChange={e=>memberForm.setData('role',e.target.value)}>{currentRole==='owner'&&<option value="admin">Yönetici</option>}<option value="operator">Operatör</option><option value="viewer">Görüntüleyici</option></select></label><button className="button" disabled={memberForm.processing}>Kullanıcı Ekle</button>{Object.values(memberForm.errors).map(x=><span className="error" key={x}>{x}</span>)}</form>}<div className="member-list">{members.map(member=><div className="member" key={member.id}><div className="member-avatar">{member.name.slice(0,1).toUpperCase()}</div><div><strong>{member.name}</strong><span>{member.email}</span></div>{canManageMembers&&manageable(member.role)?<div className="member-actions"><select aria-label={`${member.name} rolü`} value={member.role} onChange={e=>router.put(`/settings/organizations/${tenant.id}/members/${member.id}`,{role:e.target.value},{preserveScroll:true})}>{currentRole==='owner'&&<option value="owner">Firma sahibi</option>}{currentRole==='owner'&&<option value="admin">Yönetici</option>}<option value="operator">Operatör</option><option value="viewer">Görüntüleyici</option></select><button className="danger-link" type="button" onClick={()=>confirm(`${member.name} kullanıcı listesinden çıkarılsın mı?`)&&router.delete(`/settings/organizations/${tenant.id}/members/${member.id}`,{preserveScroll:true})}>Çıkar</button></div>:<span className="role">{roles[member.role]??member.role}</span>}</div>)}</div></section>}
 </AuthenticatedLayout>;
}
