import { Head, Link, router, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';
import { useState } from 'react';
import AuthenticatedLayout from '../../Layouts/AuthenticatedLayout';

type Warehouse = { id: string; name: string; code: string; is_default: boolean; is_active: boolean };
type Variant = { id: string; name: string; sku: string | null; barcode: string | null; product_name: string; quantity: number; reserved_quantity: number; available_quantity: number };
type PageLink = { url: string | null; label: string; active: boolean };
type Props = { warehouses: Warehouse[]; activeWarehouseId: string | null; variants: { data: Variant[]; links: PageLink[]; from: number | null; to: number | null; total: number } | null; filters: { search: string }; canManage: boolean };

export default function Index({ warehouses, activeWarehouseId, variants, filters, canManage }: Props) {
    const [search, setSearch] = useState(filters.search);
    const [warehouseModal, setWarehouseModal] = useState(false);
    const warehouseForm = useForm({ name: '', code: '', is_default: false });
    const activeWarehouse = warehouses.find(item => item.id === activeWarehouseId);
    const selectWarehouse = (warehouse: string) => router.get('/inventory', { warehouse, search }, { preserveState: true, replace: true });
    const submitSearch = (event: FormEvent) => { event.preventDefault(); router.get('/inventory', { warehouse: activeWarehouseId, search }, { preserveState: true, replace: true }); };
    const createWarehouse = (event: FormEvent) => { event.preventDefault(); warehouseForm.post('/warehouses', { onSuccess: () => { warehouseForm.reset(); setWarehouseModal(false); } }); };

    return <AuthenticatedLayout><Head title="Stok ve depolar" />
        <section className="page-heading heading-actions"><div><span className="eyebrow">Envanter merkezi</span><h1>Stok ve Depolar</h1><p>Varyant stoklarını depo bazında izleyin ve hareket geçmişine ulaşın.</p></div>{canManage && <button className="button" onClick={() => setWarehouseModal(true)}>+ Depo ekle</button>}</section>
        <section className="warehouse-switcher"><div className="warehouse-card"><span>Aktif depo</span><strong>{activeWarehouse?.name ?? 'Depo bulunmuyor'}</strong><small>{activeWarehouse ? `${activeWarehouse.code}${activeWarehouse.is_default ? ' · Varsayılan depo' : ''}` : 'Stok takibi için ilk deponuzu ekleyin.'}</small></div>{warehouses.length > 0 && <label>Depo değiştir<select value={activeWarehouseId ?? ''} onChange={event => selectWarehouse(event.target.value)}>{warehouses.map(warehouse => <option key={warehouse.id} value={warehouse.id}>{warehouse.name} ({warehouse.code})</option>)}</select></label>}</section>
        <section className="panel data-table-card">{variants ? <><div className="data-table-toolbar"><div><strong>Depo stokları</strong><span>{variants.total} varyant</span></div><form className="search-form" onSubmit={submitSearch}><input aria-label="Stok ara" placeholder="Ürün, varyant, SKU veya barkod ara" value={search} onChange={event => setSearch(event.target.value)} /><button className="button secondary">Ara</button></form></div>{variants.data.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Ürün / Varyant</th><th>Stok kodu</th><th>Fiziksel stok</th><th>Rezerve</th><th>Kullanılabilir</th><th /></tr></thead><tbody>{variants.data.map(variant => <tr key={variant.id}><td><strong>{variant.product_name}</strong><small>{variant.name}</small></td><td>{variant.sku ?? '—'}{variant.barcode && <small>{variant.barcode}</small>}</td><td>{variant.quantity}</td><td>{variant.reserved_quantity}</td><td><strong className={variant.available_quantity <= 0 ? 'stock-danger' : 'stock-ok'}>{variant.available_quantity}</strong></td><td><Link href={`/inventory/${variant.id}?warehouse=${activeWarehouseId}`}>Stok hareketleri</Link></td></tr>)}</tbody></table></div> : <div className="empty-state"><h2>Varyant bulunamadı</h2><p>Arama ölçütünü değiştirin veya kataloğa varyant ekleyin.</p></div>}{variants.total > 0 && <div className="pagination"><span>{variants.from}-{variants.to} / {variants.total}</span><nav>{variants.links.map((link, index) => link.url ? <Link className={link.active ? 'active' : ''} href={link.url} key={index} dangerouslySetInnerHTML={{ __html: link.label }} /> : <span key={index} dangerouslySetInnerHTML={{ __html: link.label }} />)}</nav></div>}</> : <div className="empty-state"><h2>Henüz depo yok</h2><p>Stok takibine başlamak için bir depo ekleyin.</p>{canManage && <button className="button" onClick={() => setWarehouseModal(true)}>Depo ekle</button>}</div>}</section>
        {warehouseModal && <div className="modal-layer"><button className="modal-backdrop" aria-label="Kapat" onClick={() => setWarehouseModal(false)} /><section className="modal-card" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Depo yönetimi</span><h2>Yeni depo</h2><p>Stokların tutulacağı fiziksel veya sanal depoyu tanımlayın.</p></div><button className="modal-close" onClick={() => setWarehouseModal(false)}>×</button></header><form className="form-panel" onSubmit={createWarehouse}><div className="form-row"><label>Depo adı<input autoFocus value={warehouseForm.data.name} onChange={event => warehouseForm.setData('name', event.target.value)} placeholder="Ana depo" /></label><label>Depo kodu<input value={warehouseForm.data.code} onChange={event => warehouseForm.setData('code', event.target.value.toUpperCase())} placeholder="ANA" /></label></div>{warehouses.length > 0 && <label className="checkbox"><input type="checkbox" checked={warehouseForm.data.is_default} onChange={event => warehouseForm.setData('is_default', event.target.checked)} />Varsayılan depo yap</label>}{Object.values(warehouseForm.errors).map(error => <span className="error" key={error}>{error}</span>)}<footer><button className="button secondary" type="button" onClick={() => setWarehouseModal(false)}>Vazgeç</button><button className="button" disabled={warehouseForm.processing}>Depoyu oluştur</button></footer></form></section></div>}
    </AuthenticatedLayout>;
}
