import { Head, Link, router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import AuthenticatedLayout from '../../Layouts/AuthenticatedLayout';
import ChannelLogo from '../../Components/ChannelLogo';

type Item = { id: string; name: string; quantity: number; unit_price_amount: number; discount_amount: number; tax_amount: number; total_amount: number; mapping_status: string; external_sku: string | null; external_barcode: string | null; external_product_id?: string | null; external_variant_id?: string | null; variant: { id: string; name: string; product_name: string } | null };
type Order = { id: string; external_order_id: string; external_order_number: string | null; status: string; external_status: string | null; currency: string; subtotal_amount: number; discount_amount: number; shipping_amount: number; tax_amount: number; total_amount: number; ordered_at: string; imported_at: string; customer: Record<string, string>; shipping_address: Record<string, string>; billing_address: Record<string, string>; channel: { account_id: string; name: string; account_name: string; code: string }; items: Item[] };
type StatusOption = { value: string; label: string; provider_status: string; meaning: string };
type Props = { order: Order; navigation: { previous_id: string | null; next_id: string | null }; canSync: boolean; canUpdateStatus: boolean; availableStatuses: StatusOption[] };
const money = (amount: number, currency: string) => new Intl.NumberFormat('tr-TR', { style: 'currency', currency }).format(amount / 100);
const statusLabel: Record<string, string> = { pending: 'Yeni', confirmed: 'Onaylandı', processing: 'Hazırlanıyor', shipped: 'Kargoya teslim edildi', delivered: 'Teslim edildi', cancelled: 'İptal edildi', returned: 'İade edildi' };
const fieldLabels: Record<string, string> = { first_name: 'Ad', last_name: 'Soyad', company: 'Ticari ünvan', address_1: 'Adres', address_2: 'Adres devamı', city: 'İlçe / Şehir', state: 'İl', postcode: 'Posta kodu', country: 'Ülke', phone: 'Telefon', email: 'E-posta' };

function InfoGrid({ values, empty = 'Bilgi girilmemiş' }: { values: Record<string, string>; empty?: string }) {
    const fields = Object.entries(values).filter(([, value]) => value);
    return fields.length ? <dl className="order-info-grid">{fields.map(([key, value]) => <div key={key}><dt>{fieldLabels[key] ?? key.replaceAll('_', ' ')}</dt><dd>{value}</dd></div>)}</dl> : <div className="empty-inline"><span>—</span><div><strong>{empty}</strong></div></div>;
}

export default function Show({ order, navigation, canSync, canUpdateStatus, availableStatuses }: Props) {
    const [tab, setTab] = useState<'order' | 'shipping' | 'billing'>('order');
    const [statusModal, setStatusModal] = useState(false);
    const statusForm = useForm({ status: availableStatuses[0]?.value ?? '' });
    const selectedStatus = availableStatuses.find(status => status.value === statusForm.data.status);
    const sync = () => order.channel.code === 'woocommerce'
        ? router.post(`/orders/${order.id}/refresh`)
        : router.post(`/channels/accounts/${order.channel.account_id}/trendyol/pull-orders`);
    const mapped = order.items.filter(item => item.variant).length;
    const updateStatus = (event: React.FormEvent) => {
        event.preventDefault();
        statusForm.put(`/orders/${order.id}/status`, { onSuccess: () => setStatusModal(false) });
    };

    return <AuthenticatedLayout><Head title={order.external_order_number ?? order.external_order_id} />
        <section className="page-heading order-detail-heading"><div className="order-title-row"><ChannelLogo code={order.channel.code} name={order.channel.name} size="large" /><div><span className="eyebrow">{order.channel.account_name}</span><h1>Sipariş #{order.external_order_number ?? order.external_order_id}</h1><p><span className={`status ${order.status}`}>{statusLabel[order.status] ?? order.status}</span><span>{new Date(order.ordered_at).toLocaleString('tr-TR')}</span></p></div></div><div className="order-heading-actions"><div className="order-navigation"><Link className={!navigation.previous_id ? 'disabled' : ''} href={navigation.previous_id ? `/orders/${navigation.previous_id}` : '#'}>← Önceki</Link><Link className={!navigation.next_id ? 'disabled' : ''} href={navigation.next_id ? `/orders/${navigation.next_id}` : '#'}>Sonraki →</Link></div>{canUpdateStatus && availableStatuses.length > 0 && <button className="button" onClick={() => setStatusModal(true)}>Durumu güncelle</button>}{canSync && <button className="button secondary" onClick={sync}>Pazaryerinden güncelle</button>}<Link className="button secondary" href="/orders">Siparişlere dön</Link></div></section>

        <section className="order-overview-strip"><article><span>Sipariş durumu</span><strong>{statusLabel[order.status] ?? order.status}</strong><small>Pazaryeri: {order.external_status ?? '—'}</small></article><article><span>Ürün satırı</span><strong>{order.items.length}</strong><small>{mapped}/{order.items.length} eşleşti</small></article><article><span>Genel toplam</span><strong>{money(order.total_amount, order.currency)}</strong><small>{order.currency}</small></article><article><span>İçe aktarım</span><strong>{new Date(order.imported_at).toLocaleDateString('tr-TR')}</strong><small>{new Date(order.imported_at).toLocaleTimeString('tr-TR')}</small></article></section>

        <div className="order-workspace"><section className="panel order-information"><nav className="order-info-tabs"><button className={tab === 'order' ? 'active' : ''} onClick={() => setTab('order')}>Sipariş bilgileri</button><button className={tab === 'shipping' ? 'active' : ''} onClick={() => setTab('shipping')}>Teslimat bilgileri</button><button className={tab === 'billing' ? 'active' : ''} onClick={() => setTab('billing')}>Fatura bilgileri</button></nav>{tab === 'order' && <div className="order-tab-content"><InfoGrid values={{ order_number: order.external_order_number ?? order.external_order_id, order_date: new Date(order.ordered_at).toLocaleString('tr-TR'), marketplace_status: order.external_status ?? '—', customer_name: order.customer.name ?? '—', phone: order.customer.phone ?? '—', email: order.customer.email ?? '—', currency: order.currency }} /></div>}{tab === 'shipping' && <div className="order-tab-content"><InfoGrid values={order.shipping_address} /></div>}{tab === 'billing' && <div className="order-tab-content"><InfoGrid values={order.billing_address} empty="Fatura adresi bulunmuyor" /></div>}</section>
            <aside className="panel order-total-card"><span className="eyebrow">Finansal özet</span><div className="order-totals"><span>Ara toplam <strong>{money(order.subtotal_amount, order.currency)}</strong></span><span>İndirim <strong>-{money(order.discount_amount, order.currency)}</strong></span><span>Kargo <strong>{money(order.shipping_amount, order.currency)}</strong></span><span>Vergi <strong>{money(order.tax_amount, order.currency)}</strong></span><span className="grand-total">Genel toplam <strong>{money(order.total_amount, order.currency)}</strong></span></div><div className="order-payment-note"><span>Ödeme para birimi</span><strong>{order.currency}</strong></div></aside></div>

        <section className="panel data-table-card"><div className="data-table-toolbar"><div><strong>Sipariş ürünleri</strong><span>{order.items.length} satır · {mapped} eşleşmiş</span></div></div><div className="table-wrap"><table className="data-table order-line-table"><thead><tr><th>Ürün</th><th>Pazaryeri kodları</th><th>Eşleşme</th><th>Fiyat</th><th>KDV</th><th>Adet</th><th>İndirim</th><th>Genel tutar</th></tr></thead><tbody>{order.items.map(item => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.external_sku ?? 'Pazaryeri SKU yok'}</small></td><td><code>{item.external_product_id ?? '—'}</code><small>{item.external_variant_id ? `Varyant: ${item.external_variant_id}` : item.external_barcode ?? 'Kod yok'}</small></td><td><span className={`status ${item.variant ? 'mapped' : 'unmapped'}`}>{item.variant ? 'Eşleşti' : 'Eşleşmedi'}</span>{item.variant && <small>{item.variant.product_name} · {item.variant.name}</small>}</td><td>{money(item.unit_price_amount, order.currency)}</td><td>{money(item.tax_amount, order.currency)}</td><td><strong>{item.quantity}</strong></td><td>{money(item.discount_amount, order.currency)}</td><td><strong>{money(item.total_amount, order.currency)}</strong></td></tr>)}</tbody></table></div></section>

        {statusModal && <div className="modal-layer"><button className="modal-backdrop" aria-label="Kapat" onClick={() => setStatusModal(false)} /><section className="modal-card" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Sipariş yönetimi</span><h2>Durumu güncelle</h2><p>Yeni durum önce {order.channel.name} mağazasına gönderilir. Başarılı olursa merkezi sipariş otomatik güncellenir.</p></div><button className="modal-close" type="button" onClick={() => setStatusModal(false)}>×</button></header><form className="form-panel" onSubmit={updateStatus}><label>Yeni durum<select autoFocus value={statusForm.data.status} onChange={event => statusForm.setData('status', event.target.value)}>{availableStatuses.map(status => <option key={status.value} value={status.value}>{status.label} → {status.provider_status}</option>)}</select><small>Mevcut durum: {statusLabel[order.status] ?? order.status}</small></label>{selectedStatus && <p className="notice"><strong>{statusLabel[selectedStatus.value] ?? selectedStatus.label}</strong>: {selectedStatus.meaning}</p>}{order.channel.code === 'trendyol' && <p className="notice">Trendyol paket akışında panelden yalnızca “Hazırlanıyor” adımı gönderilebilir. Sonraki durumlar pazaryerinden alınır.</p>}{Object.values(statusForm.errors).map(error => <span className="error" key={error}>{error}</span>)}<footer><button className="button secondary" type="button" onClick={() => setStatusModal(false)}>Vazgeç</button><button className="button" disabled={statusForm.processing || !statusForm.data.status}>Pazaryerine gönder</button></footer></form></section></div>}
    </AuthenticatedLayout>;
}
